package edu.unifil.lab.view;

import edu.unifil.lab.controller.UsuarioJpaController;
import edu.unifil.lab.entity.Usuario;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    // Set some attributes
    private UsuarioJpaController usuarioJpaController;
    private List<Usuario>        usuarios;
    private Usuario              auxUsuario;
    private int                  lastBtCodeUsed = 0;
    
    public LoginFrame() {        
        
        initComponents();
        setLocationRelativeTo(null); 
        
        EntityManagerFactory factory = Persistence.createEntityManagerFactory("ReservaHotelPU");
        usuarioJpaController         = new UsuarioJpaController(factory);
        usuarios                     = usuarioJpaController.findUsuarioEntities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btSubmit = new javax.swing.JButton();
        chboxPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reserva de Quartos de Hotel");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unifil/lab/images/logo-hotel.jpg"))); // NOI18N
        jLabel1.setFocusable(false);

        jLabel2.setText("Login:");
        jLabel2.setFocusable(false);

        jLabel3.setText("Password:");
        jLabel3.setFocusable(false);

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginKeyReleased(evt);
            }
        });

        btSubmit.setText("Ok");
        btSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSubmitMousePressed(evt);
            }
        });
        btSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btSubmitKeyReleased(evt);
            }
        });

        chboxPassword.setText("show password");
        chboxPassword.setFocusable(false);
        chboxPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chboxPasswordMousePressed(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtLogin)
                            .add(txtPassword)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btSubmit)
                            .add(chboxPassword))
                        .add(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(txtLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(txtPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(12, 12, 12)
                        .add(btSubmit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(chboxPassword)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chboxPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chboxPasswordMousePressed
        // Defines how to show the password
        if(!chboxPassword.isSelected()){
            txtPassword.setEchoChar((char) 0);
            txtPassword.updateUI();
        }else{
            txtPassword.setEchoChar('*');
            txtPassword.updateUI();
        }
    }//GEN-LAST:event_chboxPasswordMousePressed

    private void btSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubmitMousePressed
        
        boolean usuarioValido = false;
        auxUsuario = new Usuario();
        Usuario auxUsuario2 = null;
        auxUsuario.setLogin(txtLogin.getText().trim());
        auxUsuario.setPassword(txtPassword.getText().trim());
        
        //usuarios = usuarioJpaController.findUsuarioEntities();
        
        //for (int i=0; i<usuarios.size(); i++){
            
        //    if (usuarios.get(i).getLogin().equals(auxUsuario.getLogin()) && 
        //            usuarios.get(i).getPassword().equals(auxUsuario.getPassword())){
        //        usuarioValido = true;
        //    }
        //}
        
        if (!txtLogin.getText().trim().isEmpty() && !txtPassword.getText().trim().isEmpty()){
            
            auxUsuario2 = usuarioJpaController.findUsuarioLoginPassword(auxUsuario);
             
        }
        if(auxUsuario2 == null){
            JOptionPane.showMessageDialog(rootPane, "Usuário inválido!", "", JOptionPane.WARNING_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Bem vindo!", "", JOptionPane.INFORMATION_MESSAGE);
            ReservaHotel reservaHotel = new ReservaHotel(auxUsuario);
            reservaHotel.setVisible(true);            
            setVisible(false);
            dispose();
        }
        
    }//GEN-LAST:event_btSubmitMousePressed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10 && lastBtCodeUsed != 10) {
            this.btSubmitMousePressed(null);
        }
        lastBtCodeUsed = evt.getKeyCode();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10 && lastBtCodeUsed != 10) {
            this.btSubmitMousePressed(null);
        }
        lastBtCodeUsed = evt.getKeyCode();
    }//GEN-LAST:event_txtLoginKeyReleased

    private void btSubmitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSubmitKeyReleased
        // TODO add your handling code here:if (evt.getKeyCode() == 10) {
        if (evt.getKeyCode() == 10 && lastBtCodeUsed != 10) {
            this.btSubmitMousePressed(null);
        }
        lastBtCodeUsed = evt.getKeyCode();
    }//GEN-LAST:event_btSubmitKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.JCheckBox chboxPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
